/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TourismGuide } from "./TourismGuide";
export * as factories from "./factories";
export { TourismGuide__factory } from "./factories/TourismGuide__factory";
