/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TourismGuideInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getGuide"
      | "guides"
      | "owner"
      | "registerGuide"
      | "verifyGuide"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GuideRegistered" | "GuideVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getGuide",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "guides", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerGuide",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGuide",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getGuide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guides", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerGuide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGuide",
    data: BytesLike
  ): Result;
}

export namespace GuideRegisteredEvent {
  export type InputTuple = [guide: AddressLike, name: string, location: string];
  export type OutputTuple = [guide: string, name: string, location: string];
  export interface OutputObject {
    guide: string;
    name: string;
    location: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuideVerifiedEvent {
  export type InputTuple = [guide: AddressLike];
  export type OutputTuple = [guide: string];
  export interface OutputObject {
    guide: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TourismGuide extends BaseContract {
  connect(runner?: ContractRunner | null): TourismGuide;
  waitForDeployment(): Promise<this>;

  interface: TourismGuideInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGuide: TypedContractMethod<
    [_guide: AddressLike],
    [[string, string, boolean]],
    "view"
  >;

  guides: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        name: string;
        location: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerGuide: TypedContractMethod<
    [_name: string, _location: string],
    [void],
    "nonpayable"
  >;

  verifyGuide: TypedContractMethod<[_guide: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGuide"
  ): TypedContractMethod<
    [_guide: AddressLike],
    [[string, string, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "guides"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        name: string;
        location: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerGuide"
  ): TypedContractMethod<
    [_name: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyGuide"
  ): TypedContractMethod<[_guide: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GuideRegistered"
  ): TypedContractEvent<
    GuideRegisteredEvent.InputTuple,
    GuideRegisteredEvent.OutputTuple,
    GuideRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "GuideVerified"
  ): TypedContractEvent<
    GuideVerifiedEvent.InputTuple,
    GuideVerifiedEvent.OutputTuple,
    GuideVerifiedEvent.OutputObject
  >;

  filters: {
    "GuideRegistered(address,string,string)": TypedContractEvent<
      GuideRegisteredEvent.InputTuple,
      GuideRegisteredEvent.OutputTuple,
      GuideRegisteredEvent.OutputObject
    >;
    GuideRegistered: TypedContractEvent<
      GuideRegisteredEvent.InputTuple,
      GuideRegisteredEvent.OutputTuple,
      GuideRegisteredEvent.OutputObject
    >;

    "GuideVerified(address)": TypedContractEvent<
      GuideVerifiedEvent.InputTuple,
      GuideVerifiedEvent.OutputTuple,
      GuideVerifiedEvent.OutputObject
    >;
    GuideVerified: TypedContractEvent<
      GuideVerifiedEvent.InputTuple,
      GuideVerifiedEvent.OutputTuple,
      GuideVerifiedEvent.OutputObject
    >;
  };
}
